spring:
  application:
    name: asset05
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  web:
    resources:
      static-locations: classpath:/static/,file:${upload.path}
  datasource:
    url: jdbc:mysql://localhost:3306/asset
    username: root
    password: 929577
    driver-class-name: com.mysql.cj.jdbc.Driver

upload:
  path: D:\project\asset05\asset05\pic

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.system.asset05.entity
  configuration:
    map-underscore-to-camel-case: true